### numpy는 **리스트계산**이 쉽고 반복문을 사용하지 않아도 된다.

In [1]:
import numpy as np

In [2]:
array1 = np.arange(10)
array2 = np.arange(10,20)

In [3]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [5]:
array1 / 2

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [6]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

#### 불린연산 가능

In [7]:
array1 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [8]:
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [9]:
booleans = np.array([True, True, False, True, False])

In [10]:
np.where(booleans)

(array([0, 1, 3], dtype=int64),)

In [14]:
filter = np.where(array1 > 4) #인덱스 출력
filter

(array([5, 6, 7, 8, 9], dtype=int64),)

In [13]:
array1[filter]

array([5, 6, 7, 8, 9])

### 통계 메서드

In [15]:
array2 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [16]:
print(array2.max())
print(array2.min())

31
5


In [17]:
print(array2.mean())

15.25


In [19]:
print(array2.var())
print(array2.std())

72.1875
8.496322733983215


In [18]:
print(np.median(array2))

13.5
