In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
C = np.random.rand(3, 5)
C

array([[0.53958404, 0.20362565, 0.75658699, 0.85014056, 0.96133774],
       [0.34928352, 0.73659288, 0.92610067, 0.11050614, 0.19289702],
       [0.95554616, 0.9148698 , 0.86160479, 0.38050794, 0.35198565]])

In [6]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

행렬의 원소 받아오기

In [8]:
A[0][2]  #1행 3열

2