In [1]:
import numpy as np

In [3]:
A = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2],
    [7, 5, 6]
])

A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 7,  5,  6]])

In [4]:
C = np.random.rand(3, 5)
C

array([[0.53958404, 0.20362565, 0.75658699, 0.85014056, 0.96133774],
       [0.34928352, 0.73659288, 0.92610067, 0.11050614, 0.19289702],
       [0.95554616, 0.9148698 , 0.86160479, 0.38050794, 0.35198565]])

In [6]:
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

행렬의 원소 받아오기

In [8]:
A[0][2]  #1행 3열

2

행렬 연산

In [3]:
a = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

b = np.random.rand(3, 3)

In [4]:
a

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
b

array([[0.14632403, 0.41283479, 0.86943491],
       [0.44693836, 0.33269529, 0.79641627],
       [0.47324896, 0.83905649, 0.28956697]])

In [6]:
a + b

array([[ 1.14632403, -0.58716521,  2.86943491],
       [ 3.44693836,  2.33269529,  2.79641627],
       [ 4.47324896,  1.83905649,  2.28956697]])

In [7]:
5 * a

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [9]:
np.dot(a, b) # 내적곱

array([[0.6458836 , 1.75825248, 0.65215257],
       [2.27934674, 3.58200791, 4.78027121],
       [1.97873242, 3.66214742, 4.85328984]])

In [10]:
a @ b # 내적곱

array([[0.6458836 , 1.75825248, 0.65215257],
       [2.27934674, 3.58200791, 4.78027121],
       [1.97873242, 3.66214742, 4.85328984]])

In [11]:
a @ b +(a + 2 * b)

array([[1.93853167, 1.58392206, 4.39102239],
       [6.17322346, 6.24739849, 8.37310375],
       [6.92523034, 6.34026039, 7.43242378]])

In [12]:
a * b  # 요소별 곱하기

array([[ 0.14632403, -0.41283479,  1.73886981],
       [ 1.34081508,  0.66539057,  1.59283255],
       [ 1.89299584,  0.83905649,  0.57913394]])

전치, 단위, 역행렬

In [2]:
a = np.array([
    [1, -1, 2],
    [3, 2, 2],
    [4, 1, 2]
])

In [3]:
a

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
a_transpose = np.transpose(a) # a.T 도 간단
a_transpose

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [7]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
a @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [9]:
a_inverse = np.linalg.pinv(a) # 역행렬이 없으면 최대한 비슷한 값 리턴
a_inverse

array([[-0.2, -0.4,  0.6],
       [-0.2,  0.6, -0.4],
       [ 0.5,  0.5, -0.5]])

In [10]:
a @ a_inverse

array([[ 1.00000000e+00,  5.55111512e-16, -8.88178420e-16],
       [ 0.00000000e+00,  1.00000000e+00, -8.88178420e-16],
       [ 2.22044605e-16,  2.22044605e-16,  1.00000000e+00]])